# typed: false
# frozen_string_literal: true

# Homebrew formula for Streamline
# The Redis of Streaming - Kafka-compatible streaming platform
#
# Installation is currently blocked by design: see the generated
# STABLE ARTIFACTS region below. Once the upstream release archives and their
# signed checksum manifest are published and scripts/update-formula.sh has
# regenerated that region, installation is:
#
#   brew tap streamlinelabs/tap
#   brew install streamline
#
# Or directly:
#   brew install streamlinelabs/tap/streamline
#
# Source builds (available on the same terms, once the blocker below is
# replaced by a verified stable stanza):
#
#   brew install --HEAD streamlinelabs/tap/streamline
#   brew install --HEAD --with-moonshot streamlinelabs/tap/streamline

class Streamline < Formula
  desc "Kafka-compatible single-binary streaming platform"
  homepage "https://github.com/streamlinelabs/streamline"
  license "Apache-2.0"

  head do
    url "https://github.com/streamlinelabs/streamline.git", branch: "main"
    depends_on "rust" => :build
  end

  # Public build contract for source/HEAD installs. `brew install --HEAD
  # --with-moonshot streamlinelabs/tap/streamline` has been documented and
  # supported, so this option is part of the tap's published interface and is
  # NOT removed as cleanup: dropping it would silently turn a documented
  # invocation into "invalid option" for every existing user and script.
  #
  # Known tradeoff: `option` is deprecated for homebrew/core formulae, and
  # `brew audit --strict` flags `option`/`deprecated_option` usage there. That
  # cop is scoped to the core tap (`formula_tap != "homebrew-core"` returns
  # early), so it does not fire for this tap; if a future strict audit warns
  # anyway, the warning is accepted and documented rather than "fixed" by
  # deleting a public contract. Migrating away from it requires a deprecation
  # cycle upstream (see README "Experimental moonshot features").
  #
  # Placement is dictated by Homebrew's FormulaAudit/ComponentsOrder cop:
  # `option` sorts after the `head do` block and before `disable!` and the
  # `on_macos`/`on_linux` blocks — i.e. before the generated region below, in
  # both its blocked and its released form.
  option "with-moonshot",
         "Include experimental moonshot features (semantic search, agent memory, attestation, branches)"

  # ---------------------------------------------------------------------------
  # Stable release artifacts.
  #
  # The region between the BEGIN/END markers below is generated verbatim by
  # scripts/update-formula.sh from a signed upstream SHA256 manifest. Do not
  # hand-edit it and never substitute a placeholder, a "pending" value, or
  # `sha256 :no_check` — an unverifiable checksum is worse than no stable spec
  # at all, because Homebrew would happily install an unauthenticated archive.
  #
  # Target release: v0.4.0 (streamlinelabs/streamline). Until every one of the
  # four core archives for that tag is published AND covered by the upstream
  # checksum manifest, the region carries an explicit `disable!` blocker rather
  # than a stable spec. That is a deliberate fail-closed choice: relying on
  # Homebrew's head-only fallback would leave `brew install streamline`
  # resolving to whatever spec happens to exist, whereas `disable!` refuses
  # *every* install path — stable and `--HEAD` alike — with a maintainer-written
  # reason. HEAD installation being unavailable pre-artifact is accepted; the
  # `--with-moonshot` option above stays declared throughout, so the HEAD build
  # contract is intact the moment the blocker is replaced.
  #
  # scripts/update-formula.sh removes the blocker only by replacing this whole
  # region with a stanza whose URLs and checksums came from the core release's
  # keyless-Cosign-verified checksums.txt.
  # That stanza carries no `version` stanza: Homebrew infers the version from
  # the artifact URLs, and a stanza here — after `head do` — would fail
  # `brew style`'s component-order cop, which requires `version` before
  # `license`. Run, from the repository root:
  #
  #   ./scripts/update-formula.sh 0.4.0
  #
  # >>> STABLE ARTIFACTS BEGIN (generated by scripts/update-formula.sh) <<<
  # No verified stable release artifacts are recorded: every install path is
  # blocked until scripts/update-formula.sh replaces this region.
  disable! date: "2026-09-02", because: "no verified upstream release artifacts are published for this formula yet"
  # >>> STABLE ARTIFACTS END <<<

  def install
    if build.head?
      # Cargo feature flags are appended after the standard arguments so the
      # command stays `cargo install <std_cargo_args> --features moonshot`;
      # `--features` must be followed immediately by its value, and it is
      # emitted exactly once, only when the option was requested.
      args = std_cargo_args
      args += ["--features", "moonshot"] if build.with?("moonshot")
      system "cargo", "install", *args
    else
      # Reached only if a stable spec exists and the formula is not disabled.
      # While the generated region carries `disable!`, Homebrew refuses every
      # install before this point; this guard keeps the failure actionable if
      # the spec is ever half-generated.
      odie <<~EOS if stable.nil? || stable.url.to_s.empty?
        No verified Streamline release artifacts are recorded in this formula,
        so a stable install cannot be authenticated.

        Tap maintainers: publish the v0.4.0 archives plus the upstream SHA256
        manifest, then regenerate the stable stanza with
          ./scripts/update-formula.sh 0.4.0
      EOS

      bin.install "streamline"
      bin.install "streamline-cli" if File.exist?("streamline-cli")
    end

    odie "streamline binary not found in archive" unless (bin/"streamline").exist?

    # Generate shell completions if supported
    generate_completions_from_executable(bin/"streamline-cli", "completions") if (bin/"streamline-cli").exist?
  end

  def caveats
    <<~EOS
      Streamline has been installed!

      Quick Start:
        # Start the server
        streamline --data-dir #{var}/streamline

        # Or in playground mode (in-memory, demo topics)
        streamline --playground

      Service Management:
        # Start as a background service
        brew services start streamline

        # Stop the service
        brew services stop streamline

        # View logs
        tail -f #{var}/log/streamline.log

      CLI Usage:
        # Produce a message
        streamline-cli produce demo -m "Hello, Streamline!"

        # Consume messages
        streamline-cli consume demo --from-beginning

        # List topics
        streamline-cli topics list

      Kafka Clients:
        Streamline is Kafka-compatible. Connect any Kafka client to localhost:9092.

      Data Directory: #{var}/streamline
      Log File:       #{var}/log/streamline.log

      Documentation:
        https://github.com/streamlinelabs/streamline
    EOS
  end

  service do
    run [opt_bin/"streamline", "--data-dir", var/"streamline"]
    keep_alive true
    working_dir var
    log_path var/"log/streamline.log"
    error_log_path var/"log/streamline.log"
  end

  test do
    expected_version = build.head? ? /\d+\.\d+\.\d+/ : version.to_s

    # Verify binaries exist and are executable
    assert_path_exists bin/"streamline"
    assert_predicate bin/"streamline", :executable?

    # Test --version output
    assert_match expected_version, shell_output("#{bin}/streamline --version")

    # Test --help output
    assert_match "streamline", shell_output("#{bin}/streamline --help")

    if (bin/"streamline-cli").exist?
      assert_predicate bin/"streamline-cli", :executable?
      assert_match "streamline-cli", shell_output("#{bin}/streamline-cli --help")
    end

    # Test server starts, responds to health check, and serves Kafka protocol
    kafka_port = free_port
    http_port = free_port
    pid = fork do
      exec bin/"streamline",
           "--listen-addr", "127.0.0.1:#{kafka_port}",
           "--http-addr", "127.0.0.1:#{http_port}",
           "--data-dir", testpath/"data",
           "--in-memory"
    end

    begin
      ready = false
      20.times do
        if Kernel.system(
          "curl", "-fsS", "http://127.0.0.1:#{http_port}/health",
          out: File::NULL, err: File::NULL
        )
          ready = true
          break
        end
        sleep 1
      end
      assert ready, "Streamline health endpoint did not become ready"

      # Health endpoint responds
      health_output = shell_output("curl -fsS http://127.0.0.1:#{http_port}/health")
      assert_match(/ok|healthy|alive/i, health_output)

      # Info endpoint returns server version
      info_output = shell_output("curl -fsS http://127.0.0.1:#{http_port}/info")
      assert_match expected_version, info_output

      # Topics list endpoint responds (empty list is fine)
      topics_output = shell_output("curl -fsS http://127.0.0.1:#{http_port}/api/v1/topics")
      assert_match(/\[/, topics_output)

      # Kafka protocol port is listening (TCP connect test)
      assert shell_output("nc -z 127.0.0.1 #{kafka_port} 2>&1; echo $?").strip.end_with?("0"),
             "Kafka protocol port #{kafka_port} should be listening"
    ensure
      Process.kill("TERM", pid)
      Process.wait(pid)
    end
  end
end
