#!/usr/bin/env bash
set -euo pipefail

# update-formula.sh — Regenerate the stable release stanza of the Homebrew
# formula from a *verified* upstream checksum manifest.
#
# Usage:
#   ./scripts/update-formula.sh <version> [--create-pr] [--dry-run]
#
# Options:
#   --create-pr    Create a git branch and open a PR via gh CLI after updating
#   --dry-run      Show the stanza that would be generated, without writing
#
# Environment:
#   STREAMLINE_REQUIRE_SIGNATURE   "1" (default) or "0". Nothing else is
#                                  accepted — "true", "yes" and "2" are hard
#                                  errors rather than silently truthy.
#   The production trust policy is fixed to the core release workflow's keyless
#   Sigstore identity and GitHub Actions OIDC issuer. It is not configured by a
#   repository secret or a developer-managed signing key.
#
# Integrity contract (all of it must hold before the formula is touched):
#   1. An upstream checksum manifest for the release must exist and be readable.
#   2. Unless STREAMLINE_REQUIRE_SIGNATURE=0, checksums.txt.sig and
#      checksums.txt.pem must verify with cosign against the exact core release
#      workflow identity and GitHub Actions OIDC issuer.
#   3. Every expected archive must be listed in the manifest under its exact
#      expected name.
#   4. Every archive must download, be non-empty, and hash to the manifest value.
#   5. Every archive member name must be safe (no absolute paths, no "..") and
#      the archive must contain the `streamline` binary.
#   6. The fully rendered formula must parse as Ruby and pass the release
#      metadata gate *before* the checked-in formula is touched; installation
#      is a single same-directory rename.
# If any target fails any step, the formula is left byte-for-byte unchanged.
#
# No checksum is ever invented: hashes come from the archives and are checked
# against the signed manifest.

usage() {
  sed -n '3,41p' "$0"
}

if [ "$#" -lt 1 ]; then
  usage >&2
  exit 2
fi

VERSION="$1"
shift
CREATE_PR=false
DRY_RUN=false
for arg in "$@"; do
  case "$arg" in
    --create-pr) CREATE_PR=true ;;
    --dry-run) DRY_RUN=true ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "❌ Unknown option: $arg" >&2
      exit 2
      ;;
  esac
done

# Strict semantic version. Rejects shell metacharacters by construction.
if ! printf '%s' "${VERSION}" |
  grep -Eq '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z.-]+)?$'; then
  echo "❌ Invalid version '${VERSION}'. Expected semantic version, e.g. 0.3.0" >&2
  exit 2
fi

REPO="streamlinelabs/streamline"
FORMULA="${STREAMLINE_FORMULA:-streamline.rb}"
BASE_URL="${STREAMLINE_RELEASE_BASE_URL:-https://github.com/${REPO}/releases/download/v${VERSION}}"
MANIFEST_NAME="checksums.txt"
SIGNATURE_NAME="checksums.txt.sig"
CERTIFICATE_NAME="checksums.txt.pem"
REQUIRE_SIGNATURE="${STREAMLINE_REQUIRE_SIGNATURE:-1}"
COSIGN_IDENTITY="https://github.com/StreamlineLabs/streamline/.github/workflows/release.yml@refs/tags/v${VERSION}"
COSIGN_OIDC_ISSUER="https://token.actions.githubusercontent.com"
EMPTY_HASH="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

# Signature enforcement is a security control, so its switch is parsed
# strictly: exactly "1" (required, the default) or exactly "0" (disabled for
# hermetic fixture tests). Anything else — "true", "yes", "2", "" — is an
# operator error and must not be guessed into a truthy or falsy value.
case "${REQUIRE_SIGNATURE}" in
  0 | 1) ;;
  *)
    echo "❌ STREAMLINE_REQUIRE_SIGNATURE must be exactly '0' or '1' (got '${REQUIRE_SIGNATURE}')." >&2
    echo "   Values such as 'true', 'yes' or '2' are rejected rather than interpreted." >&2
    echo "   Signature verification is required unless it is explicitly set to 0," >&2
    echo "   which is only ever appropriate for local fixture releases." >&2
    exit 2
    ;;
esac

BEGIN_MARKER="  # >>> STABLE ARTIFACTS BEGIN (generated by scripts/update-formula.sh) <<<"
END_MARKER="  # >>> STABLE ARTIFACTS END <<<"

TARGETS=(
  "aarch64-apple-darwin"
  "x86_64-apple-darwin"
  "aarch64-unknown-linux-gnu"
  "x86_64-unknown-linux-gnu"
)

if [ ! -f "${FORMULA}" ]; then
  echo "❌ Formula file '${FORMULA}' not found. Run from the repository root." >&2
  exit 2
fi

if ! grep -qF "${BEGIN_MARKER}" "${FORMULA}" || ! grep -qF "${END_MARKER}" "${FORMULA}"; then
  echo "❌ '${FORMULA}' has no generated stable-artifacts region." >&2
  echo "   Expected the BEGIN/END markers emitted by this script." >&2
  exit 2
fi

WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT

echo "==> Updating formula for Streamline v${VERSION}"
[ "$DRY_RUN" = true ] && echo "    (dry-run — the formula will not be modified)"

# ---------------------------------------------------------------------------
# Step 1: fetch the upstream checksum manifest. Required, no fallback.
# ---------------------------------------------------------------------------
MANIFEST="${WORKDIR}/${MANIFEST_NAME}"
echo "==> Fetching checksum manifest ${MANIFEST_NAME}"
if ! curl -fsSL -o "${MANIFEST}" "${BASE_URL}/${MANIFEST_NAME}"; then
  echo "❌ Checksum manifest '${BASE_URL}/${MANIFEST_NAME}' is unavailable." >&2
  echo "   Refusing to update the formula from unauthenticated artifacts." >&2
  exit 1
fi
if [ ! -s "${MANIFEST}" ]; then
  echo "❌ Checksum manifest is empty. Formula not modified." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Step 2: verify the detached keyless Sigstore signature over checksums.txt.
#
# The certificate identity is the exact tagged core release workflow and the
# issuer is GitHub Actions OIDC. A valid signature from any other workflow,
# repository, issuer, branch, or tag is rejected.
# ---------------------------------------------------------------------------
if [ "${REQUIRE_SIGNATURE}" = "1" ]; then
  if ! command -v cosign >/dev/null 2>&1; then
    echo "❌ cosign is required to verify the core release checksum manifest." >&2
    exit 1
  fi

  SIGNATURE="${WORKDIR}/${SIGNATURE_NAME}"
  CERTIFICATE="${WORKDIR}/${CERTIFICATE_NAME}"
  echo "==> Fetching checksum signature and certificate"
  if ! curl -fsSL -o "${SIGNATURE}" "${BASE_URL}/${SIGNATURE_NAME}"; then
    echo "❌ Manifest signature '${BASE_URL}/${SIGNATURE_NAME}' is unavailable." >&2
    echo "   Set STREAMLINE_REQUIRE_SIGNATURE=0 only for hermetic tests against" >&2
    echo "   a local fixture release; never for a real publish." >&2
    exit 1
  fi
  if ! curl -fsSL -o "${CERTIFICATE}" "${BASE_URL}/${CERTIFICATE_NAME}"; then
    echo "❌ Manifest certificate '${BASE_URL}/${CERTIFICATE_NAME}' is unavailable." >&2
    echo "   Formula not modified." >&2
    exit 1
  fi

  COSIGN_OUT="${WORKDIR}/cosign.out"
  if ! cosign verify-blob \
    --certificate "${CERTIFICATE}" \
    --signature "${SIGNATURE}" \
    --certificate-identity "${COSIGN_IDENTITY}" \
    --certificate-oidc-issuer "${COSIGN_OIDC_ISSUER}" \
    "${MANIFEST}" >"${COSIGN_OUT}" 2>&1; then
    echo "❌ Manifest signature verification failed. Formula not modified." >&2
    sed 's/^/   /' "${COSIGN_OUT}" >&2
    exit 1
  fi

  echo "   ✅ Signature verified for tagged core release workflow v${VERSION}"
else
  echo "==> ⚠️  Signature verification disabled (STREAMLINE_REQUIRE_SIGNATURE=0)"
  echo "    This is only valid for hermetic fixture runs; never for a publish."
fi

# ---------------------------------------------------------------------------
# Step 3-5: validate every expected archive against the manifest.
# ---------------------------------------------------------------------------
FAILURES=()
HASHES=()

manifest_hash_for() {
  # Manifest lines are "<64-hex><space><space-or-asterisk><filename>".
  awk -v want="$1" '
    { name = $2; sub(/^\*/, "", name) }
    name == want && $1 ~ /^[a-f0-9]{64}$/ { print $1; found++ }
    END { exit(found == 1 ? 0 : 1) }
  ' "${MANIFEST}"
}

validate_archive_entries() {
  local archive="$1"
  local entries
  if ! entries=$(tar -tzf "${archive}" 2>/dev/null); then
    echo "not a readable gzip tar archive"
    return 1
  fi
  if [ -z "${entries}" ]; then
    echo "archive is empty"
    return 1
  fi
  while IFS= read -r entry; do
    case "${entry}" in
      /* | */../* | ../* | *$'\n'*)
        echo "unsafe archive member '${entry}'"
        return 1
        ;;
    esac
    if ! printf '%s' "${entry}" | grep -Eq '^[A-Za-z0-9._][A-Za-z0-9._/-]*$'; then
      echo "unexpected archive member name '${entry}'"
      return 1
    fi
  done <<<"${entries}"
  # A here-string, not a pipe: `grep -Eq` exits at its first match, and a tar
  # listing is the one producer here whose output can exceed the pipe buffer,
  # so piping it would risk SIGPIPE (exit 141) tripping `set -o pipefail`.
  # Single-value `printf | grep` checks above are always far below the buffer
  # size and cannot be interrupted mid-write, so they stay as they are.
  if ! grep -Eq '(^|/)streamline$' <<<"${entries}"; then
    echo "archive does not contain the 'streamline' binary"
    return 1
  fi
  return 0
}

for i in "${!TARGETS[@]}"; do
  target="${TARGETS[$i]}"
  tarball="streamline-v${VERSION}-${target}.tar.gz"
  url="${BASE_URL}/${tarball}"

  echo "==> ${target}"

  if ! expected=$(manifest_hash_for "${tarball}"); then
    echo "   ❌ '${tarball}' has no unique SHA256 entry in the manifest"
    FAILURES+=("${target}: absent from checksum manifest")
    continue
  fi

  if ! curl -fsSL -o "${WORKDIR}/${tarball}" "${url}"; then
    echo "   ❌ Failed to download ${url}"
    FAILURES+=("${target}: archive not downloadable")
    continue
  fi

  actual=$(shasum -a 256 "${WORKDIR}/${tarball}" | awk '{print $1}')
  if [ "${actual}" = "${EMPTY_HASH}" ]; then
    echo "   ❌ Downloaded archive is empty (0 bytes)"
    FAILURES+=("${target}: empty archive")
    continue
  fi
  if [ "${actual}" != "${expected}" ]; then
    echo "   ❌ Checksum mismatch (manifest ${expected}, archive ${actual})"
    FAILURES+=("${target}: checksum does not match the signed manifest")
    continue
  fi

  if ! entry_error=$(validate_archive_entries "${WORKDIR}/${tarball}"); then
    echo "   ❌ ${entry_error}"
    FAILURES+=("${target}: ${entry_error}")
    continue
  fi

  echo "   ✅ ${actual}"
  HASHES[i]="${actual}"
done

if [ "${#FAILURES[@]}" -gt 0 ]; then
  echo "==> Release v${VERSION} is not fully verifiable:" >&2
  for failure in "${FAILURES[@]}"; do
    echo "    - ${failure}" >&2
  done
  echo "    Formula was not modified." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Render the stable stanza. Written only after every target verified.
#
# No explicit `version` stanza is emitted. Homebrew infers the version from the
# artifact URLs (`.../streamline-v<version>-<target>.tar.gz`), so a stanza would
# be redundant; and it could only be written here — after `head do` — where
# `brew style`'s FormulaAudit/ComponentsOrder cop rejects it, because `version`
# must precede `license`. The version is therefore carried by the four URLs
# alone, and check-formula-metadata.sh enforces that all four agree on it.
# ---------------------------------------------------------------------------
BLOCK="${WORKDIR}/stable.rb"
{
  printf '%s\n' "${BEGIN_MARKER}"
  printf '  # Homebrew infers the version from these artifact URLs; an explicit\n'
  printf '  # "version" stanza would be redundant and out of component order here.\n'
  printf '  on_macos do\n'
  printf '    on_arm do\n'
  printf '      url "%s/streamline-v%s-aarch64-apple-darwin.tar.gz"\n' "${BASE_URL}" "${VERSION}"
  printf '      sha256 "%s"\n' "${HASHES[0]}"
  printf '    end\n'
  printf '    on_intel do\n'
  printf '      url "%s/streamline-v%s-x86_64-apple-darwin.tar.gz"\n' "${BASE_URL}" "${VERSION}"
  printf '      sha256 "%s"\n' "${HASHES[1]}"
  printf '    end\n'
  printf '  end\n\n'
  printf '  on_linux do\n'
  printf '    on_arm do\n'
  printf '      url "%s/streamline-v%s-aarch64-unknown-linux-gnu.tar.gz"\n' "${BASE_URL}" "${VERSION}"
  printf '      sha256 "%s"\n' "${HASHES[2]}"
  printf '    end\n'
  printf '    on_intel do\n'
  printf '      url "%s/streamline-v%s-x86_64-unknown-linux-gnu.tar.gz"\n' "${BASE_URL}" "${VERSION}"
  printf '      sha256 "%s"\n' "${HASHES[3]}"
  printf '    end\n'
  printf '  end\n'
  printf '%s\n' "${END_MARKER}"
} >"${BLOCK}"

if [ "$DRY_RUN" = true ]; then
  echo "==> Dry run — generated stanza:"
  sed 's/^/    /' "${BLOCK}"
  exit 0
fi

RENDERED="${WORKDIR}/formula.rb"
awk -v begin_marker="${BEGIN_MARKER}" -v end_marker="${END_MARKER}" -v block="${BLOCK}" '
  $0 == begin_marker { inside = 1; while ((getline line < block) > 0) print line; close(block); next }
  $0 == end_marker   { inside = 0; next }
  !inside            { print }
' "${FORMULA}" >"${RENDERED}"

# ---------------------------------------------------------------------------
# Gate the *candidate* before the checked-in formula is touched at all. Every
# failure path above and below this point leaves ${FORMULA} byte-identical,
# and the single mutation is an atomic same-directory rename, so an interrupt
# can never leave a half-written formula on disk.
# ---------------------------------------------------------------------------
if ! ruby -c "${RENDERED}" >/dev/null; then
  echo "❌ Generated formula is not valid Ruby. Formula not modified." >&2
  exit 1
fi

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
if ! "${SCRIPT_DIR}/check-formula-metadata.sh" --mode release "${RENDERED}"; then
  echo "❌ Generated formula failed the release metadata gate. Formula not modified." >&2
  exit 1
fi

FORMULA_DIR=$(cd "$(dirname "${FORMULA}")" && pwd)
FORMULA_BASE=$(basename "${FORMULA}")
STAGED="${FORMULA_DIR}/.${FORMULA_BASE}.staged.$$"
trap 'rm -rf "$WORKDIR"; rm -f "$STAGED"' EXIT

# Same filesystem and same directory, so the rename below is atomic. Copying
# the original first preserves its mode and ownership.
cp -p "${FORMULA}" "${STAGED}"
cat "${RENDERED}" >"${STAGED}"
mv -f "${STAGED}" "${FORMULA}"

echo "==> Formula updated to v${VERSION}"

# ---------------------------------------------------------------------------
# Optional PR publication.
# ---------------------------------------------------------------------------
if [ "$CREATE_PR" = true ]; then
  if ! command -v gh >/dev/null 2>&1; then
    echo "❌ GitHub CLI (gh) is required for --create-pr." >&2
    exit 1
  fi

  BRANCH="update/v${VERSION}"
  echo "==> Creating PR for v${VERSION}..."

  git checkout -b "${BRANCH}" 2>/dev/null || git switch "${BRANCH}"
  git add "${FORMULA}"
  git commit -m "chore: update formula to v${VERSION}

Regenerate the stable stanza from the verified upstream checksum manifest."

  git push -u origin "${BRANCH}"
  gh pr create \
    --title "Update Streamline to v${VERSION}" \
    --body "Automated formula update for Streamline v${VERSION}.

- Regenerated stable stanza from the keyless-Cosign-verified upstream checksums.txt
- Four artifact URLs (which Homebrew infers the version from) and four checksums" \
    --label "automated"

  echo "==> PR created successfully!"
fi
